image: node:latest

cache:
    paths:
        - node_modules/
        - .build/
        - api/config.js
        - src/config.js

stages:
    - build
    - deploy

# before_script:
#     - npm i

# Development
build:dev:
    stage: build
    only:
        - dev
    tags:
        - dev
    script:
        - cp -f /var/www/configs/web.config.js src/config.js
        - cp -f /var/www/configs/api.config.js api/config.js
        - npm i
        - npm run build

deploy:dev:
    stage: deploy
    only:
        - dev
    tags:
        - dev
    script:
        - pm2 restart ecosystem.config.js
        - sudo mkdir -p /var/www/website
        - sudo cp -rf .build/. /var/www/website

# Production
build:prod:
    stage: build
    only:
        - master
    tags:
        - production
    script:
        - cp -f /var/www/configs/web.config.js src/config.js
        - cp -f /var/www/configs/api.config.js api/config.js
        - npm i
        - npm run build

deploy:prod:
    stage: deploy
    only:
        - master
    tags:
        - production
    script:
        - pm2 restart ecosystem.config.js
        - sudo mkdir -p /var/www/website
        - sudo cp -rf .build/. /var/www/website
