image: node:latest

cache:
    paths:
        - node_modules/
        - .build/
        - api/config.js
        - src/config.js


stages:
    - build
    - deploy

build:
    stage: build
    script:
        - npm i
        - npm run build
    # Add artifacts later, because now it's about 35MB.
    # artifacts:
    #     paths:
    #         - .build/

deploy:
    stage: deploy
    script:
        - echo "Deploy to prod server"
        # - npm run build
        - echo "$(ls -a)"
        - mkdir -p /var/www/website
        - cp -a .build/. /var/www/website
        - npm run api-pm2

    only:
        - dev
