image: node:latest

cache:
    paths:
        - node_modules/
        - .build/
        - api/config.js
        - src/config.js


# stages:
#     - build
#     - deploy

# build:
#     stage: build
#     environment:
#         name: staging
#         url: http://disordered.ru
#     only:
#         - dev
#     script:
#         - npm i
#         - npm run build
    # Add artifacts later, because now it's about 35MB.
    # artifacts:
    #     paths:
    #         - .build/

staging_build_deploy:
    stage: deploy
    environment:
        name: staging
        url: http://disordered.ru
    only:
        - dev
    script:
        - echo "Building"
        - npm i
        - npm run build
        - echo "Deploying"
        - mkdir -p /var/www/website
        - cp -rf .build/. /var/www/website
        - npm run api-pm2
    # Add artifacts later, because now it's about 35MB.
    # artifacts:
    #     paths:
    #         - .build/
