image: node:latest

cache:
    paths:
        - node_modules/

# stages:
#     - build
#     - deploy

# build:
#     stage: build
#     environment:
#         name: staging
#         url: http://disordered.ru
#     only:
#         - dev
#     script:
#         - npm i
#         - npm run build
    # Add artifacts later, because now it's about 35MB.
    # artifacts:
    #     paths:
    #         - .build/

staging_build_deploy:
    stage: deploy
    environment:
        name: staging
        url: http://disordered.ru
    only:
        - dev
    script:
        # - echo "Building"
        - cp -f /var/www/configs/web.config.js src/config.js
        - cp -f /var/www/configs/api.config.js api/config.js
        # - cp -f /var/www/configs/build.config.json buildconfig.json
        - npm i
        - npm run build
        # - echo "Deploying"
        - mkdir -p /var/www/website
        - rm -rf /var/www/website
        - cp -rf .build/. /var/www/website
        - npm run api-pm2
